### ISSUE TITLE
Is it possible to set a max height for the edit area?

### ISSUE THREAD

**Issue by nivv** [sparksuite/simplemde-markdown-editor#205]
I would like to set a max-height and then allow the user to scroll inside the edit area. If I set a max-height it's respected but scrolling is disabled. 

Any ideas?

**Comment by nivv** [comment]
Figured it out, did like below:

``` css
.CodeMirror,
.CodeMirror-scroll {
    max-height: 300px;
}
```

Add these styles to still have 100% height in full screen mode:

``` css
.CodeMirror-fullscreen.CodeMirror {
    max-height: none;
}

.CodeMirror-fullscreen .CodeMirror-scroll {
    max-height: none;
}
```
