### ISSUE TITLE
Unintended fullscreen behavior when SimpleMDE is in a Bootstrap modal

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#263]
Both fullscreen and split fullscreen do not work very well when in a Bootstrap modal.

**Comment by Psychokrameur** [comment]
I work with ExtJs, and it's also doesn't work very well when using SimpleMDE in a modal Window.
Did not know Bootstrap Modal but I suppose it's quite similar.

**Comment by Psychokrameur** [comment]
Any idea on how to fix this?

**Comment by WesCossick** [comment]
I believe it is a CSS issue, but I have not started working on it myself. I'd be open to a PR that fixes this.

**Comment by WesCossick** [comment]
Possible solution, move SimpleMDE to root of body on full screen, then place it back after. Would need to be a version 2 feature.

**Comment by Psychokrameur** [comment]
Thanks for the workaround, I will test that.

**Comment by joelcuevas** [comment]
How about adding a `simplemde-fullscreen` class to the body when fullscreen mode is active, and providing CSS styles that temporarily alter the Bootstrap/ExtJs modal window size and position?

Quick-and-dirty fix for Bootstrap:

```javascript
var mde = new SimpleMDE();

mde.codemirror.on('refresh', function() {
    if (mde.isFullscreenActive()) {
        $('body').addClass('simplemde-fullscreen');
    } else {
        $('body').removeClass('simplemde-fullscreen');
    }
});
```

```css
.simplemde-fullscreen .modal-dialog {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    max-width: 100%;
    margin: 0;
}
```
