### ISSUE TITLE
Auto adjust preview height

### ISSUE THREAD

**Issue by NickSeagull** [sparksuite/simplemde-markdown-editor#483]
When I make SimpleMDE to auto-adjust its height by adjusting it in the CodeMirror CSS classes, it works as expected:

```css
.CodeMirror, .CodeMirror-scroll {
    height: auto;
    min-height: 70px;
}
```

![S1](https://i.stack.imgur.com/1fPSv.jpg)

The problem comes when I call `togglePreview()` on it, it makes the `editor-preview` div render a scrollbar, as it doesn't adjust the height accordingly.

![S2](https://i.stack.imgur.com/vEm5x.jpg)

Is this the correct behavior? If not how could I make the preview adjust itself too?
