### ISSUE TITLE
Dedicated toolbar buttons for H1, H2, H3

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/simplemde-markdown-editor#61]
@madmax stated:

You can easly make nice h1 icon using font-awesome:

http://mad.xan.pl/s/1GoHSZQ77L/

``` JS
className: "fa fa-header fa-header-1",
```

``` CSS
.fa-header-1:after {
  font-size: 50%;
  vertical-align: text-bottom;
  content: "1";
}
```
