### ISSUE TITLE
Multiple Textareas Different Heights

### ISSUE THREAD

**Issue by jasonlewis** [sparksuite/simplemde-markdown-editor#64]
There doesn't seem to be a way to set different heights for multiple textareas.

Any chance of an option being added for this instead of it being entirely controlled by a single CSS class?

**Comment by WesCossick** [comment]
Just place each editor inside of a parent element:

``` css
.parent1 .CodeMirror {
    height: 300px;
}

.parent2 .CodeMirror {
    height: 500px;
}
```
