### ISSUE TITLE
Empty separator

### ISSUE THREAD

**Issue by MR-H0200** [sparksuite/simplemde-markdown-editor#723]
```
new SimpleMDE({
			hideIcons: ['guide',],
			showIcons: [ 'undo', 'redo'],
			element: $('.textarea')
		});
```

![image](https://user-images.githubusercontent.com/13794605/48308442-13c9b080-e58b-11e8-9306-c61caf9688cf.png)

there is a empty separator near undo and redo

**Comment by dninomiya** [comment]
I made this compromise 😢 

```css
  .separator + .separator {
    display: none;
  }
```
