### ISSUE TITLE
Feature request: editor as viewer, preview mode

### ISSUE THREAD

**Issue by Be1zebub** [sparksuite/simplemde-markdown-editor#847]
Markdown editor can be used as markdown viewer.
I use this hack todo this:
```js
const mde = new SimpleMDE({
	element: document.querySelector("#profile-bio > .markdown-preview > textarea"),
	toolbar: ["preview"],
	initialValue: "Lorem **ipsum**."
});

// actiate preview mode
mde.togglePreview();
```
```css
/* hide all editor related ui, for preview only mde */
.markdown-preview > .CodeMirror,
.markdown-preview > .CodeMirror > .editor-preview {
	background-color: transparent;
	padding: 0;
}

.markdown-preview > .CodeMirror > .editor-preview {
	display: contents;
}

.markdown-preview > .CodeMirror > .CodeMirror-scroll {
	display: none;
}

.markdown-preview > .editor-toolbar {
	display: none !important;
}
.markdown-preview > .editor-statusbar {
	display: none !important;
}
```

I would like to request the addition of this feature, with activation via option - like:
```js
const mde = new SimpleMDE({
	element: document.querySelector("#profile-bio > textarea"),
	initialValue: "Lorem **ipsum**.",
	previewMode: true
});
```
